version: '3.7'
services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_CONSOLE_ADDRESS: ":9001"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - server_net
    volumes:
      - minio-data:/data



  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    networks:
      - server_net
    depends_on:
      - minio

volumes:
  minio-data:

networks:
  server_net:
    driver: bridge