version: '3.7'
services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_CONSOLE_ADDRESS: ":9001"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - server_net
    volumes:
      - minio-data:/data



  fastapi_app:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/flaskpostgre
      MINIO_URL: http://minio:9000
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "8000:8000"
    networks:
      - server_net
    depends_on:
      - minio
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flaskpostgre
    ports:
      - "5432:5432"

volumes:
  minio-data:
  postgres_data:

networks:
  server_net:
    driver: bridge
